@startuml
boundary "CLI" as UI
box "Orchagent" #LightGrey
    control IntfMgrD
    control IntfsOrch
end box
participant kernel
box "DB" #LightBlue
    database CONFIG_DB
    database APPL_DB
    database ASIC_DB
end box

UI -> CONFIG_DB: config SAG global MAC address
IntfMgrD <-- CONFIG_DB
UI -> CONFIG_DB: enable SAG on the VLAN interface
IntfMgrD <-- CONFIG_DB
UI -> CONFIG_DB: config interface IP address on the VLAN interface
IntfMgrD <-- CONFIG_DB
IntfMgrD -> kernel: create VLAN interface and change to SAG MAC address
IntfMgrD -> APPL_DB: create INTF_TABLE entry with SAG MAC address and IP address entry
IntfsOrch <-- APPL_DB
IntfsOrch -> ASIC_DB: create router interface and change to SAG MAC address
IntfMgrD -> APPL_DB: config VLAN interface IP
IntfsOrch <-- APPL_DB
IntfsOrch -> ASIC_DB: add IP2ME route and net route
group Disable SAG on the VLAN interface
    UI -> CONFIG_DB: disable SAG on the VLAN interface
    IntfMgrD <-- CONFIG_DB
    IntfMgrD -> kernel: change VLAN interface's MAC address to CPU MAC address
    IntfMgrD -> APPL_DB: Modify INTF_TABLE entry from SAG MAC address to CPU MAC address
    IntfsOrch <-- APPL_DB
    IntfsOrch -> ASIC_DB: change router interface's MAC address to CPU MAC address
end
@enduml