@startuml
' Online Server: https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000
' Basic examples: https://plantuml.com/sequence-diagram#5e05164bff244555
' Declaring participant: https://plantuml.com/sequence-diagram#5d2ed256d73a7298
' Message to Self: https://plantuml.com/sequence-diagram#f5050860884ddf31
' Lifeline Activation and Destruction: https://plantuml.com/sequence-diagram#5cc0040514e70f7b
' Incoming and outgoing messages: https://plantuml.com/sequence-diagram#05984b1743e67542
' Comments: https://plantuml.com/commons#8413c683b4b27cc3

participant "[[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/build_templates/per_namespace/swss.service.j2 swss.service.j2]]" as swss.service.j2
participant "[[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/scripts/swss.sh swss.sh]]" as swss.sh
participant "[[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/build_templates/docker_image_ctl.j2 docker_image_ctl.j2]]" as docker_image_ctl.j2
participant "[[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/src/sonic-ctrmgrd/ctrmgr/container container]]" as container
participant "[[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/image_config/misc/docker-wait-any docker-wait-any]]" as dockerwaitany

[-> swss.service.j2: sudo systemctl start swss
activate swss.service.j2
swss.service.j2 -> swss.sh: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/build_templates/per_namespace/swss.service.j2#L24 /usr/local/bin/swss.sh start]]
activate swss.sh
swss.sh -> swss.sh: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/scripts/swss.sh#L169-L179 sonic-db-cli APPL_DB FLUSHDB\nsonic-db-cli ASIC_DB FLUSHDB\nsonic-db-cli COUNTERS_DB FLUSHDB\nsonic-db-cli FLEX_COUNTER_DB FLUSHDB\nsonic-db-cli GB_ASIC_DB FLUSHDB\nsonic-db-cli GB_COUNTERS_DB FLUSHDB\nsonic-db-cli RESTAPI_DB FLUSHDB\nsonic-db-cli APPL_STATE_DB FLUSHDB]]
swss.sh -> docker_image_ctl.j2: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/scripts/swss.sh#L186 /usr/bin/swss.sh start]]
activate docker_image_ctl.j2
docker_image_ctl.j2 -> container: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/build_templates/docker_image_ctl.j2#L351 /usr/local/bin/container start swss]]
activate container
container -> container: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/src/sonic-ctrmgrd/ctrmgr/container#L125 container.start()]]
docker_image_ctl.j2 <- container
deactivate container
swss.sh <- docker_image_ctl.j2
deactivate docker_image_ctl.j2
swss.service.j2 <- swss.sh
deactivate swss.sh
swss.service.j2 -> swss.sh: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/build_templates/per_namespace/swss.service.j2#L25 /usr/local/bin/swss.sh wait]]
activate swss.sh
swss.sh -> swss.sh: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/scripts/swss.sh#L113-L129 /bin/systemctl start syncd\n/bin/systemctl start radv\n/bin/systemctl start bgp\n/bin/systemctl start dhcp_relay]]
swss.sh -> swss.sh: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/scripts/swss.sh#L209-L243 Allow some time for peer container to start]]
swss.sh -> dockerwaitany: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/scripts/swss.sh#L258 /usr/bin/docker-wait-any -s swss -d syncd dhcp_relay]]
activate dockerwaitany
dockerwaitany -> dockerwaitany: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/image_config/misc/docker-wait-any#L100 t.start()]]
activate dockerwaitany
dockerwaitany -> dockerwaitany: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/image_config/misc/docker-wait-any#L52 docker_client.wait('swss')]]
dockerwaitany -> dockerwaitany: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/image_config/misc/docker-wait-any#L63 g_thread_exit_event.set()]]
deactivate dockerwaitany
dockerwaitany -> dockerwaitany: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/image_config/misc/docker-wait-any#L100 t.start()]]
activate dockerwaitany
dockerwaitany -> dockerwaitany: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/image_config/misc/docker-wait-any#L52 docker_client.wait('syncd')]]
dockerwaitany -> dockerwaitany: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/image_config/misc/docker-wait-any#L63 g_thread_exit_event.set()]]
deactivate dockerwaitany
dockerwaitany -> dockerwaitany: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/image_config/misc/docker-wait-any#L104 g_thread_exit_event.wait()]]
swss.sh <- dockerwaitany
deactivate dockerwaitany
swss.service.j2 <- swss.sh
deactivate swss.sh
deactivate swss.service.j2
[-> swss.service.j2: sudo warm-reboot
activate swss.service.j2
swss.service.j2 -> swss.sh: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/build_templates/per_namespace/swss.service.j2#L24 /usr/local/bin/swss.sh start]]
activate swss.sh
swss.sh -> docker_image_ctl.j2: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/scripts/swss.sh#L186 /usr/bin/swss.sh start]]
activate docker_image_ctl.j2
docker_image_ctl.j2 -> container: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/build_templates/docker_image_ctl.j2#L351 /usr/local/bin/container start swss]]
activate container
container -> container: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/src/sonic-ctrmgrd/ctrmgr/container#L125 container.start()]]
docker_image_ctl.j2 <- container
deactivate container
swss.sh <- docker_image_ctl.j2
deactivate docker_image_ctl.j2
swss.service.j2 <- swss.sh
deactivate swss.sh
swss.service.j2 -> swss.sh: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/build_templates/per_namespace/swss.service.j2#L25 /usr/local/bin/swss.sh wait]]
activate swss.sh
swss.sh -> swss.sh: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/scripts/swss.sh#L209-L243 Allow some time for peer container to start]]
swss.sh -> dockerwaitany: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/scripts/swss.sh#L258 /usr/bin/docker-wait-any -s swss -d syncd dhcp_relay]]
activate dockerwaitany
dockerwaitany -> dockerwaitany: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/image_config/misc/docker-wait-any#L100 t.start()]]
activate dockerwaitany
dockerwaitany -> dockerwaitany: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/image_config/misc/docker-wait-any#L52 docker_client.wait('swss')]]
dockerwaitany -> dockerwaitany: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/image_config/misc/docker-wait-any#L63 g_thread_exit_event.set()]]
deactivate dockerwaitany
dockerwaitany -> dockerwaitany: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/image_config/misc/docker-wait-any#L100 t.start()]]
activate dockerwaitany
dockerwaitany -> dockerwaitany: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/image_config/misc/docker-wait-any#L52 docker_client.wait('syncd')]]
dockerwaitany -> dockerwaitany: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/image_config/misc/docker-wait-any#L63 g_thread_exit_event.set()]]
deactivate dockerwaitany
dockerwaitany -> dockerwaitany: [[https://github.com/sonic-net/sonic-buildimage/blob/df4312f7ef4b8b808320be3df9c09c84b4a3e423/files/image_config/misc/docker-wait-any#L104 g_thread_exit_event.wait()]]
swss.sh <- dockerwaitany
deactivate dockerwaitany
swss.service.j2 <- swss.sh
deactivate swss.sh
deactivate swss.service.j2
@enduml
